POST http://localhost:8080/api/v1/user/student-reg
Content-Type: application/json

{
    "firstName" : "Evidence",
    "middleName": "Opeoluwa",
    "lastName": "Adejuwon",
    "admissionClass": "SS3",
    "academicYear": "2021/2022",
    "placeOfBirth": "Port-Hacourt",
    "stateOfBirth": "Abia",
    "email": "glory@glory.com"
}
###

POST http://localhost:8080/api/v1/user/student
Content-Type: application/json

{
    "email": "glory@glory.com"
}